{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Functions"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "On this lab we will put to practice some of the concepts we have learned on this past few days.\n",
    "\n",
    "`NOTE: On this lab you should try to write all the functions yourself using only the most basic of python syntax and without functions such as len, count, sum, max, min, in, etc. Give it a try. üßëüèª‚Äçüíªüë©üèª‚Äçüíª`\n",
    "\n",
    "The cell after each exercise contains a few tests to check if your function works as expected."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from mod.testing import *\n",
    "import unittest"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Write a function that returns the greater of two numbers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def greater(a,b):\n",
    "    if a>b:\n",
    "        return a\n",
    "    else:\n",
    "        return b\n",
    "greater(1,4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.075s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_greater(greater)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Now write a function that returns the largest element on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "('Largest element is:', 99)"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "list = [10, 20, 4, 45, 99]\n",
    "def greatest(list):\n",
    "    list.sort() \n",
    "    return \"Largest element is:\", list[-1] \n",
    "greatest(list)\n",
    "#No entiendo por qu√© me da error."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "list = [10, 20, 4, 45, 99]\n",
    "def greatest(list):\n",
    "    greatest=0\n",
    "    for i in list:\n",
    "        if i > greatest:\n",
    "            greatest=i\n",
    "    return greatest"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.080s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_greatest(greatest)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Write a function that sums all the elements on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "6\n"
     ]
    }
   ],
   "source": [
    "def sum_all(numbers, oper):\n",
    "    if oper==\"+\":\n",
    "        return sum(numbers)\n",
    "    if oper==\"*\":\n",
    "        producto=1\n",
    "        for n in numbers:\n",
    "            producto*=n\n",
    "        return producto\n",
    "numbers=[1,2,3]\n",
    "oper=\"+\"\n",
    "\n",
    "print(oper_all(numbers,oper))\n",
    "\n",
    "#Esta funci√≥n suma por qu√© me da error? :("
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "6\n"
     ]
    }
   ],
   "source": [
    "numbers=[1,2,3]\n",
    "\n",
    "def sum_all(numbers):\n",
    "    suma = 0\n",
    "    for i in numbers:\n",
    "        suma = suma + i\n",
    "    return suma\n",
    "print(sum_all(numbers))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.072s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_sum(sum_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Write another function that multiplies all the elements on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "64\n"
     ]
    }
   ],
   "source": [
    "def mult_all(numbers):\n",
    "    producto=1\n",
    "    for n in numbers:\n",
    "        producto*=n\n",
    "    return producto\n",
    "numeros=[1,4,8,2]\n",
    "\n",
    "print(mult_all(numeros))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.071s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_mult(mult_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Now combine those two ideas and write a function that receives a list and either \"+\" or \"*\" and outputs acordingly"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "6\n"
     ]
    }
   ],
   "source": [
    "def oper_all(numbers, oper):\n",
    "    if oper==\"+\":\n",
    "        return sum(numbers)\n",
    "    if oper==\"*\":\n",
    "        producto=1\n",
    "        for n in numbers:\n",
    "            producto*=n\n",
    "        return producto\n",
    "numbers=[1,2,3]\n",
    "oper=\"+\"\n",
    "\n",
    "print(oper_all(numbers,oper))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.083s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_operations(oper_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Write a function that returns the factorial of a number."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [],
   "source": [
    "def factorial(n):\n",
    "    producto=1\n",
    "    for i in range(1,n+1):\n",
    "        producto*=i\n",
    "    return producto\n",
    "\n",
    "n=4"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.089s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_factorial(factorial)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Write a function that takes a list and returns a list of the unique values.\n",
    "\n",
    "`NOTE: You cannot use set. ü§î`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1, 2, 3, 8]\n"
     ]
    }
   ],
   "source": [
    "numb=[1,2,2,3,3,8,8]\n",
    "\n",
    "def unique(numb):\n",
    "    unicos=[]    \n",
    "    for n in numb:\n",
    "        if n not in unicos:\n",
    "            unicos.append(n)\n",
    "    return unicos\n",
    "    \n",
    "print(unique(numb))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.139s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_unique(unique)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Write a function that returns the mode of a list, i.e.: the element that appears the most times.\n",
    "`NOTE: You should not use count... üßê`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_mode.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 127, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "TypeError: 'list' object is not callable\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.115s\n",
      "\n",
      "FAILED (errors=100)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_mode(mode_counter)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Write a function that calculates the standard deviation of a list.\n",
    "`NOTE: Do not use any libraries or already built functions. üòâ`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2.1908902300206643\n"
     ]
    }
   ],
   "source": [
    "lista=[10,8,10,8,8,4]\n",
    "\n",
    "def st_dev(lista):\n",
    "    media_lista=sum(lista)/len(lista)\n",
    "    varianza1=[]\n",
    "    varianza2=[]\n",
    "    varianza=[]\n",
    "    desv_std=0\n",
    "    for i in lista:\n",
    "        varianza1.append(i-media_lista)\n",
    "    for i in varianza1:\n",
    "        varianza2.append(i**2)\n",
    "    for i in varianza2:\n",
    "        varianza=(sum(varianza2)/(len(lista)-1))\n",
    "    return varianza**0.5\n",
    "\n",
    "print(st_dev(lista))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.080s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_stdev(st_dev)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 10. Write a function to check if a string is a pangram, i.e.: if it contains all the letters of the alphabet at least once."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 72,
   "metadata": {},
   "outputs": [],
   "source": [
    "def pangram(string):\n",
    "    alphabet='a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'\n",
    "    for i in alphabet:\n",
    "        if i not in string.lower():\n",
    "            return False\n",
    "    return True"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 73,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "..............................\n",
      "----------------------------------------------------------------------\n",
      "Ran 30 tests in 0.019s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_pangram(pangram)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 11. Write a function that receives a string of comma separated words and returns a string of comma separated words sorted alphabetically.\n",
    "\n",
    "`NOTE: You may use sorted but not split and definitely no join! ü§™`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sort_alpha(string):\n",
    "    pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'csua,dqwoyj,epxeoywng,gyhyishd,htjgsnr,i[103 chars]ocpz' : Should be csua,dqwoyj,epxeoywng,gyhyishd,htjgsnr,ivnygg,kwrfjhvvv,lshotpv,lyqwunnp,nbtxyojmi,nfamttlwpy,nhfbmdui,qknz,qljakzyi,ranv,rmdco,rotazw,uypb,xoqocpz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bpvkzubejk,czali,dfsovzfdm,dsshmmjy,efmb[133 chars]wnsq' : Should be bpvkzubejk,czali,dfsovzfdm,dsshmmjy,efmboytl,emgdfuwzt,ieqvl,ksmobmvc,mhkjzkobv,oqckbjkps,ozxy,pdxbcilrn,qpkttk,spwqxun,tooc,txis,vieaye,vsnhmyayy,vxpislkw,xrikionena,yyiihtwnsq\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bfsyeqvvs,bvtni,cuhlzsfszy,dfzafmj,fcajb[129 chars]eeag' : Should be bfsyeqvvs,bvtni,cuhlzsfszy,dfzafmj,fcajbzctnl,gpvzuufv,idulcxbnvq,iumcek,koojzj,lpeekzphg,mdmwn,mwgmgmle,nuvhli,nvye,obbhihoos,peawb,qmuigd,sfarrmfyvt,uvxjvc,xhqerzu,yzieeag\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'agqaoip,ajul,dzrhp,eyvurbdcz,gvgm,idshhk[96 chars]zxgd' : Should be agqaoip,ajul,dzrhp,eyvurbdcz,gvgm,idshhkvqmc,jxxhsn,kflj,mnxxhsxp,mpzdeww,owdwcrytb,swaznqpb,tfxrpd,tlspxhtsof,uqxv,vbrkya,wbqzqf,wlbaf,zxgd\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bcdvpl,bhlaw,bjgumvv,bzodnzpy,ecbd,kjvp,[48 chars]qscl' : Should be bcdvpl,bhlaw,bjgumvv,bzodnzpy,ecbd,kjvp,sthxmrt,syyiv,ubmhmvo,uofhgcebjn,wrfxl,yecugvl,zqscl\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'ekibdxjsy,erhpl,fwhm,gdmgna,gjszjba,huuh[111 chars]qdft' : Should be ekibdxjsy,erhpl,fwhm,gdmgna,gjszjba,huuho,jjnml,jjnxvnbut,mrcp,oirxkhkdm,oxgpoy,phniciyxd,qlcxmk,qyubk,rihvnwh,rmqcmd,tjvazyszc,tsopjbips,vmiiym,whivhzqdft\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bgumjpol,fqvjsznhh,gpwb,gzthljkrcy,hpqly[93 chars]qkmj' : Should be bgumjpol,fqvjsznhh,gpwb,gzthljkrcy,hpqlyuq,hrtonoft,jgubsjvtp,jxwoiql,litwjnjqh,pwcmpigksm,qidkuksv,qpzlaivfrt,uorezf,vtiqqaloeb,xbemqkmj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'ceuwpvh,dfvgdkmg,dzskllvf,fvmworbhjw,ohhdy,zbvggmi' : Should be ceuwpvh,dfvgdkmg,dzskllvf,fvmworbhjw,ohhdy,zbvggmi\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'cvuhcysvrm,lezklguif,otgqnrdmi,uytndg,xnvnei' : Should be cvuhcysvrm,lezklguif,otgqnrdmi,uytndg,xnvnei\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'aiqfg,brxopnutzm,enqjbr,fpuypktufv,gowzf[116 chars]zzow' : Should be aiqfg,brxopnutzm,enqjbr,fpuypktufv,gowzfqu,lcpzdqm,llxhbfwrfq,luerrufj,mkyoj,mkzry,okrlzr,qfeamcjlg,qvlnakh,rnajgu,silsdy,tvjfedspkk,upio,view,xbahg,xvtfcu,zzow\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'azxrrot,jftepytze,llbusai,lvjwcxtpkt' : Should be azxrrot,jftepytze,llbusai,lvjwcxtpkt\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'cavwxydvr,eqknly,erlxaarb,gndizdlr,goxeh[97 chars]wskd' : Should be cavwxydvr,eqknly,erlxaarb,gndizdlr,goxehyovqd,hipxmypnm,hmar,jfnek,mqvfa,oyspbglwq,qgveeimdbd,qnjrefz,rtngmhy,uydhycj,veishabw,vvrjxerqe,wskd\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'aszvwtbl,cvpzjkggzk,fdzqicis,gxmwspp,kfi[81 chars]rvwl' : Should be aszvwtbl,cvpzjkggzk,fdzqicis,gxmwspp,kfioc,kmqw,lnzn,ltgxbajpgp,odsqn,qzrqrkxr,rtzqgm,shkanky,txcu,wnlpjr,xznhx,yesr,yredrvwl\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'aeuyxidoq,beubyqttmq,bnoxqgy,cbntzsokgl,[156 chars]pchj' : Should be aeuyxidoq,beubyqttmq,bnoxqgy,cbntzsokgl,dkujktdc,doscwouoho,erlmp,fstrcv,fubiwq,gxndkmdls,hgvh,hpgrcry,lwffajq,mbjzfgujs,mjijmjl,psif,tirfcttv,tkehptorb,ucvfzvgrb,xxtoj,yhcnwtzkrt,ynxhasmzvm,ytxmxpchj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'ayqg,bgbkvuyd,cngl,dazmymibyw,popivwf,qsizi,rcphlj,rnccjk,vkvxvzjlb' : Should be ayqg,bgbkvuyd,cngl,dazmymibyw,popivwf,qsizi,rcphlj,rnccjk,vkvxvzjlb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'duyfj,exqwjaoquu,htpg,huaewi,ifdis,ispti[145 chars]stlc' : Should be duyfj,exqwjaoquu,htpg,huaewi,ifdis,ispti,iukzfs,jbzwpvxo,jqnn,kkkhnir,lnpspolptx,lvodoncdj,lwqziijfw,lypd,mptj,raity,tfaqkuhg,tnxjipq,tsqfvd,vnaeccactw,vyoaumi,ymeh,ymgkoma,zkwlnmmvsp,zstlc\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'afqnsceis,aqxwnl,cung,dqii,eabx,ejehwz,j[128 chars]hpey' : Should be afqnsceis,aqxwnl,cung,dqii,eabx,ejehwz,jekv,nolzblm,orkvv,qgvtjarhtz,qilgari,qkcwk,recqgxhxs,rnksclqkpy,slat,stfkp,tmnqhchsq,txglvapng,uoad,vffzy,vnhnqiy,wbnasfx,yqkrdqhpey\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'aistk,bwwckjlu,czjahobv,ljhzz,tdpn,ybse' : Should be aistk,bwwckjlu,czjahobv,ljhzz,tdpn,ybse\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bcttryydmm,drdxwytho,eljyiytqzc,fkvj,gof[65 chars]ucyc' : Should be bcttryydmm,drdxwytho,eljyiytqzc,fkvj,gofd,lnqf,pbmd,ppvhpeok,shnkcex,sqchkwgbvq,wwfr,wyunxvouu,ybzaur,zzkucyc\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'dnvd,hmiuic,idgcnsq,ilha,lfrdcuux,nelhn,rilfneo,sldn,xtaoycu,zvan' : Should be dnvd,hmiuic,idgcnsq,ilha,lfrdcuux,nelhn,rilfneo,sldn,xtaoycu,zvan\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bowgfhj,fdul,ffnmrkq,gqffwn,haroxsa,iizz[128 chars]tndd' : Should be bowgfhj,fdul,ffnmrkq,gqffwn,haroxsa,iizz,juan,keqsqlofdl,kjsikrllp,nkvmew,nqfqww,pgzfjyyoyl,pxaxcfpt,qygpagxq,sckgzd,sgasejrtx,svynz,tkjjrss,xauoi,xxonecp,yxfqaop,zrlqytndd\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'avyq,cjspbnviva,dfjamfla,dlnfdnt,dtkwvol[111 chars]wjlt' : Should be avyq,cjspbnviva,dfjamfla,dlnfdnt,dtkwvol,eudkgzbjsj,iduzfcj,iyru,jkqhwp,jljtjuadrl,mdzphuwa,peheeojn,pmflbkpa,sgfmpjsnfc,vwnnjdtkw,xgrnhnf,ykpaskpimb,ywjlt\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'fcuwo,julzeihbm,lskmijuow,tusrtxo' : Should be fcuwo,julzeihbm,lskmijuow,tusrtxo\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'avxqmca,bevnqcuan,fblx,fzhck,kacnnws,nfp[60 chars]kzwe' : Should be avxqmca,bevnqcuan,fblx,fzhck,kacnnws,nfpxc,nfvzixbs,qlnt,sadcqaxp,saho,spireqps,stgf,xxnouucg,yrdolzkzwe\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'aizqtqpm,hcqifxngp,husqvkmbgv,hxxuwcr,id[82 chars]dazo' : Should be aizqtqpm,hcqifxngp,husqvkmbgv,hxxuwcr,idruoqc,ltwrjlrr,mchr,ooedvqi,plrrfoi,pxvn,rvev,tlobuzzoc,ubffjnvobr,uswjuzvm,ykmgvfdazo\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'ahwi,dsmrscpor,nlqkth,qtfuydbn' : Should be ahwi,dsmrscpor,nlqkth,qtfuydbn\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'angdeb,bxfmsxz,ccvhuyt,cibtpvvw,dkbksvr,[139 chars]shpe' : Should be angdeb,bxfmsxz,ccvhuyt,cibtpvvw,dkbksvr,ghpqclqjp,hcfklafa,jvisqvsyod,ltuzc,ppkvutk,qpkdufis,sahvy,tcrrqzmcj,titz,tufjw,ulfgnlnhm,vvocefsiv,vyuujksx,xlcjpzkuj,xzllywt,yyvoeu,zhrosshpe\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'auccvar,biseqlq,fwdqc,svrwggvx,vzzzwhb' : Should be auccvar,biseqlq,fwdqc,svrwggvx,vzzzwhb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bcot,btox,cqmv,dwknhe,edfy,frmkpdeig,hxt[73 chars]aven' : Should be bcot,btox,cqmv,dwknhe,edfy,frmkpdeig,hxtmd,hyijcarw,nmpzi,qworheicyx,rrredefhz,ucrpevtbcm,vppjzz,ygcp,yokwjc,zqphaven\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'cgnk,drvmo,fgyhn,gqzkkd,hbzc,idfuvctvl,k[93 chars]ophe' : Should be cgnk,drvmo,fgyhn,gqzkkd,hbzc,idfuvctvl,kuyuga,ndympbwfp,ogjeu,omkbz,otxlslty,pstypy,roxp,smtxk,svmbutyhdv,tpkiq,trrxlmlnpg,xcutu,zaubophe\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'acgiu,awral,bpewfn,dias,fqmoum,fsrxxsw,k[94 chars]iksh' : Should be acgiu,awral,bpewfn,dias,fqmoum,fsrxxsw,kjhnj,lmdc,mqjxnsnbu,ohmlhxhmu,pcyqpaq,pvmkjqhum,qgtsf,qldftwsurc,rndgfxfvr,vyqzf,xlxf,ypxw,zdsiksh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'blcthrc,efyybf,eqfcahgs,ffpcmaih,fltqszf[116 chars]mipv' : Should be blcthrc,efyybf,eqfcahgs,ffpcmaih,fltqszfnv,gemgcvdq,gpyb,ifaarjmjly,jfcch,kdwbqunxh,mykntg,qhiaicd,qrlzpyqti,rlgqhztihm,scwdgk,tfhmtsikra,wlvb,wwqipqwnwd,xtmipv\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'ayzvtn,cojdfhkdy,cwloicnfv,dyvtavpm,enbz[154 chars]gphb' : Should be ayzvtn,cojdfhkdy,cwloicnfv,dyvtavpm,enbzwnkfij,hudyeekxya,jpfddic,kgkeyx,mkqlna,nexlkwr,oeyzwwmyie,ozmlww,pcwgho,punfxdugu,rztdu,sqyyflh,tinqv,ttyx,ukmgel,uljk,wrqlyp,yuycfbbivi,zgiugswe,zjmo,zqgphb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'cpyczj,hlma,ifyfmjsz,imcvma,mllf,nqteur,[53 chars]hqkl' : Should be cpyczj,hlma,ifyfmjsz,imcvma,mllf,nqteur,oybik,pgdwz,slnxxho,unnggse,vfltpnr,vgwo,xlbfyxo,xpmmhqkl\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'ofnrrn,sbmuxqvcr,uafurxzrtp,xdiuz,xjna' : Should be ofnrrn,sbmuxqvcr,uafurxzrtp,xdiuz,xjna\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'apmamxt,awwtimddz,cvuzsksy,dhiws,dmrdnd,[124 chars]wmdt' : Should be apmamxt,awwtimddz,cvuzsksy,dhiws,dmrdnd,emuhencz,evre,eyng,fmlnbjko,hzeywrzxdy,jilpifcyoj,jnlgt,mnfv,rdkxgi,rfbwc,rmezzfbz,rojlydpbev,rtaqhuh,scsfprhcu,ungrnmp,wtolwmdt\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'awlpr,cjwummkzdm,cueeka,hucocaeerd,ifton[69 chars]rtwu' : Should be awlpr,cjwummkzdm,cueeka,hucocaeerd,iftonatqqw,iqas,otwnk,qydjhkk,skvpav,tkxrq,tursc,ufwzczu,vlegsp,vwram,yqjirtwu\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'btmktfierl,fiydsqhxa,gdds,pmyxszqy,qszi' : Should be btmktfierl,fiydsqhxa,gdds,pmyxszqy,qszi\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bfnooj,cbtvtcebe,cwmlmmlqo,daoxfin,gflok[95 chars]saax' : Should be bfnooj,cbtvtcebe,cwmlmmlqo,daoxfin,gfloklpp,hdbowxumzt,hqclslvvgq,hunb,krugagyt,ovxmrozr,psucu,qakoglh,qvfqv,rizfbo,ugaj,vihupwqsxh,zdusaax\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bpzxxc,czxyrg,djbwt,ecujflc,fvvsugw,fxwg[125 chars]auyz' : Should be bpzxxc,czxyrg,djbwt,ecujflc,fvvsugw,fxwgaxm,izcbcayplx,kgywqys,kknspyfrtp,ktoodooma,kwgqwpz,kyprrose,ogkmmjcdtf,oxrnm,ptwtwbg,rilsgdzt,rpnrir,uzqbv,vkgdqrnvbx,znwqbiauyz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'atfrhtafo,bgnfti,btmfadhr,cresdg,dfrm,ej[144 chars]folx' : Should be atfrhtafo,bgnfti,btmfadhr,cresdg,dfrm,ejfoljp,fakkmkih,gxorizwnz,htsuvy,imepyjjm,inshtbjiz,jweo,nbnv,ogerr,plob,qdki,rssckbmmpm,rtfznv,unyo,vsxtclmkj,vzenyvid,wjgslz,xfbo,xoprsau,ynvynfolx\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'ebuvefpjk,fxilncjz,ldqrxoky,nrubxkx,vemiad,ytnjvelh' : Should be ebuvefpjk,fxilncjz,ldqrxoky,nrubxkx,vemiad,ytnjvelh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bbbww,cdvodebok,dffcdot,fuosmmsnm,lvtny,[36 chars]zvwo' : Should be bbbww,cdvodebok,dffcdot,fuosmmsnm,lvtny,qwpmxf,shkcfdzzea,tyspqshyef,uxhxz,uzvwo\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'acysjct,cqylwgxuf,fdjslzwvz,hzhucyngwh,j[43 chars]efqr' : Should be acysjct,cqylwgxuf,fdjslzwvz,hzhucyngwh,jmbanvm,mnzub,ncdktzibqd,odys,orhupa,ssaj,xuefqr\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'eeswks,iobinffki,jlggaftyyj,jvjboccvmc,l[84 chars]onha' : Should be eeswks,iobinffki,jlggaftyyj,jvjboccvmc,lbdvoy,luztpig,mlvf,mtzflpvo,nynfzm,ogvj,pgiuxzyylq,psqexro,uhbas,xdmrlihn,yipaatz,yqonha\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'adurzgzd,ajcumbzu,cjmqst,dxpfizxzxr,ebnx[136 chars]oarh' : Should be adurzgzd,ajcumbzu,cjmqst,dxpfizxzxr,ebnxwjyfo,feylcge,hbdnuihsf,hpgypy,hxpn,nooadrxlf,ptpqbpagwk,pvvqkjp,qnotmxgwej,qwlc,qypfs,skpalxao,sywleftor,uxkvgndco,vujrdx,ylynsojt,ynthoarh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'gsddq,nxqvkcz,sjawkp,ysqmshpcje' : Should be gsddq,nxqvkcz,sjawkp,ysqmshpcje\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'apeodqdwhf,bklve,cmmhcu,dthikebmmc,fawrg[149 chars]ussm' : Should be apeodqdwhf,bklve,cmmhcu,dthikebmmc,fawrgqbtgh,fdlwi,hpwd,ilnfq,lhkpf,mdvu,mlzwsvgnas,mnptxrhiiv,mwdnrq,ojvo,osxqgsu,owlaabj,qelzyblg,qtqpvkovg,tkzrz,ueoyhyysdk,uhlj,xfwazlaoki,xlxuv,yfmmk,zussm\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'fyxzua,jacjkd,jslnvmda,ldtcbktjey,mkasqw[36 chars]bhll' : Should be fyxzua,jacjkd,jslnvmda,ldtcbktjey,mkasqwhq,pozzzxefb,pxwbpkm,qdszg,voyti,wnhbhll\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'boynuhuwb,cfmpukir,eqez,fwpyk,gdqzzgixkg[60 chars]obel' : Should be boynuhuwb,cfmpukir,eqez,fwpyk,gdqzzgixkg,kfpxwsowqd,ooloea,qhgaknnve,rlgote,tmxlynrivt,vkkvttt,wjpogobel\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'fymcop,lvwgpgopq,netsxkkeyj,nixcoql,oroqvt,recilulpt,ucvu,uzvw,ynusj' : Should be fymcop,lvwgpgopq,netsxkkeyj,nixcoql,oroqvt,recilulpt,ucvu,uzvw,ynusj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'afdouuujb,ceyoft,cvvugf,cxda,ftrmp,gssxp[120 chars]rwly' : Should be afdouuujb,ceyoft,cvvugf,cxda,ftrmp,gssxpx,jbqhlxcpgx,nervraif,proakak,ptosbmbuv,qdzxhunhab,shghciy,trjqltc,ttbasqp,tyfeu,utmvbjy,vaeaocrin,veoiwrlvy,wxsyttt,zwfrwly\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'cudmjyeaht,ebhlgsmet,eqmfd,gnkymfcw,gtpi[99 chars]sdzd' : Should be cudmjyeaht,ebhlgsmet,eqmfd,gnkymfcw,gtpi,hpejz,jakk,jhmb,jzyvj,kdbby,lqdbrx,ozcftaji,qbvmd,vavxtcgpd,vyzstqsdxg,witjmtomsh,xaqddmmlnq,xkqdmsdzd\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'acfu,auclt,awjztj,fsdcp,fvxqfijfwx,glxdi[113 chars]urcx' : Should be acfu,auclt,awjztj,fsdcp,fvxqfijfwx,glxdido,iidinqsp,ijyqsmn,jvyfcqgg,otysfztalx,pseearsvs,qevbfxk,rglk,rxffvpqer,tftub,uktfikioj,uwcr,vdkoyujshn,ygvv,yxiurcx\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'byaaac,dkkjl,ewgksssmh,fveb,ggqt,gtzlh,h[102 chars]orab' : Should be byaaac,dkkjl,ewgksssmh,fveb,ggqt,gtzlh,hyeasbb,iwpm,jcmfdvmi,jddr,klrhcqicd,mfivewzxsf,oncqc,psnvji,puabn,rroizuuhb,ukdh,vsrhgbmcr,xpslbtzp,yeorab\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'edcjcdlh,fxrsws,fzaijlamy,mkalxx,qhlzjwf,qpvkahzd,sffcyj' : Should be edcjcdlh,fxrsws,fzaijlamy,mkalxx,qhlzjwf,qpvkahzd,sffcyj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'dpoymrpt,eaers,fhbdatm,jgbpjg,jnysedg,le[64 chars]akeh' : Should be dpoymrpt,eaers,fhbdatm,jgbpjg,jnysedg,lewmcpdmc,lshpxerfhd,nbdpanli,qcdlaqkmju,rbmdaalkow,ssqfewuru,waikakeh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'cqkuqzoucq,cyphsesly,drfiehhq,emah,etukx[164 chars]zcpa' : Should be cqkuqzoucq,cyphsesly,drfiehhq,emah,etukxazv,gqjxniaca,hkcol,hmoaozytmg,iaswijhvar,jrob,jyvch,kjizdg,kossmjdk,lbdemb,njcmv,nwgxup,pxepilmmz,rpblsuo,skvxn,ugoghpdii,vffvwhfcit,wavxe,wtrwmwp,ydacgmfmuu,zvukwzcpa\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'devan,dlbxnrq,emlalnw,ihyubosqy,nhdyhx,q[58 chars]xrvn' : Should be devan,dlbxnrq,emlalnw,ihyubosqy,nhdyhx,qftaup,qjgvuf,qzfegfajhu,stvsuhp,taccwkhkrk,txkhbptn,xxmz,xxrvn\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'gxuvldmosn,liubu,mmrukx,ockluknoo,prafhhgqd,txdmv,ufumtfrk,xromq' : Should be gxuvldmosn,liubu,mmrukx,ockluknoo,prafhhgqd,txdmv,ufumtfrk,xromq\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'aendcw,ajidzvsl,aovu,dfebiys,djoz,fgjytj[110 chars]qwzu' : Should be aendcw,ajidzvsl,aovu,dfebiys,djoz,fgjytjuwh,jrvnvt,lxqziaffu,ossxwglwcc,poyrixj,pqsprnc,qtowtuovf,tgrsi,uolreyu,uqdrkp,wjcbguuj,ykxueyly,ynyvyvcw,yxuxqwzu\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'avikspb,bigajf,dacxgwa,efjjmyoqy,jvnn,nfpgl,tyadohpxbh,ychykjkoad,ynpwtuvxlw' : Should be avikspb,bigajf,dacxgwa,efjjmyoqy,jvnn,nfpgl,tyadohpxbh,ychykjkoad,ynpwtuvxlw\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'coigqykixm,czwi,jtetic,kjpihsruq,kupzzqh[113 chars]wrpj' : Should be coigqykixm,czwi,jtetic,kjpihsruq,kupzzqh,mcxw,mivckw,mtfnew,nqiaaugt,pgpesh,prsy,qatpqivqs,qitc,qudqvdmig,rajouark,sgiuvad,srfhbjebo,thsittmhq,tslgrynlk,wrpj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'epsy,mzdmvoqcjo,uhhqlmr,yzppsact,zrutxuddku' : Should be epsy,mzdmvoqcjo,uhhqlmr,yzppsact,zrutxuddku\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'fbsogjeka,geel,jiyhty,zwdfy' : Should be fbsogjeka,geel,jiyhty,zwdfy\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'ejxzj,fprqif,inhemqgk,wxxicuabaq,xdldfmhtk' : Should be ejxzj,fprqif,inhemqgk,wxxicuabaq,xdldfmhtk\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bknofydpr,bmuuq,djyr,dntgtu,dysx,eshsyrq[152 chars]qnwk' : Should be bknofydpr,bmuuq,djyr,dntgtu,dysx,eshsyrqnzd,eszkjuhgh,fsbnxhwgxw,gzca,hqww,iiktmobr,kgcy,kymvmkgbm,nrwuromret,oaoc,oklox,qdyian,rtcseo,tdrqcrxyw,umhtmvgppl,vcrvt,wtvpfnpthh,yndvil,ynlknqigte,yqnwk\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'ahgfk,bbujkazj,bzfdyrpgap,ceboyxpal,hegr[150 chars]yjeb' : Should be ahgfk,bbujkazj,bzfdyrpgap,ceboyxpal,hegrgusj,hgniwkvfd,iwjvgsovi,jutwe,khfs,ljtn,lohzdythp,lxquvhm,nrswbvds,nzwixwz,ojfzqrrrl,qfvaxxc,smqyffidh,uhphmkst,ukzogkt,uvrrodk,yxdgvvxt,zxnmyzrp,zyzyjeb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'ndsux,oasrosf,sjmhagb,udtkrst' : Should be ndsux,oasrosf,sjmhagb,udtkrst\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'cbwciyrp,dvkzsu,jjajpgvyg,jzyfi,msmutnwlon,ptftcxo,uenoiyl,xjpjjzufw' : Should be cbwciyrp,dvkzsu,jjajpgvyg,jzyfi,msmutnwlon,ptftcxo,uenoiyl,xjpjjzufw\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bnhkrpj,icgkf,iosgbt,ipbuhx,javlwc,jfpyd[118 chars]oamd' : Should be bnhkrpj,icgkf,iosgbt,ipbuhx,javlwc,jfpydloz,kkcyo,lxgyna,mezblicyat,mfhzqaon,nwwxao,snlqtwcv,svwhwch,tids,ubgtgvzdya,vjlaezwbm,wnfzafudmm,wrjmgn,yblvvb,zfvf,zoamd\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'aplq,cglggvu,fuwo,gynoi,hcsr,hzuvvirh,ie[123 chars]ucto' : Should be aplq,cglggvu,fuwo,gynoi,hcsr,hzuvvirh,iexmd,ifeptwgev,kmbskne,lsgfsol,oqbozime,otccpr,poonk,pysuczigy,qguaqi,qgvdl,rnjeon,sgur,umyeap,vidwovwib,xcnukki,xmmz,zlko,zucto\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'aveqpvzsbh,cqvp,izla,jlpmxwu,ltipenh,senbcz,tfrygfxk,yeiqsrtnfg,zuxexjdhyj' : Should be aveqpvzsbh,cqvp,izla,jlpmxwu,ltipenh,senbcz,tfrygfxk,yeiqsrtnfg,zuxexjdhyj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'mqjsjdhpa,prmndzly,sewciqf,uhbsakr' : Should be mqjsjdhpa,prmndzly,sewciqf,uhbsakr\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'altjntq,emda,evbfxwramy,iedllikor,jtju,o[66 chars]zblf' : Should be altjntq,emda,evbfxwramy,iedllikor,jtju,oftoydojj,ohcf,qjkqdzorz,rvndg,sqgvw,whaw,wuzahwwbka,xajhrkj,zzxyvhzblf\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'ayixgavh,fhizgnazcd,fjcrmi,fvpm,hjukks,i[111 chars]ivmx' : Should be ayixgavh,fhizgnazcd,fjcrmi,fvpm,hjukks,iimn,iwekavy,kpdktzzaei,lxbgeop,mrnffmxo,mrwefccu,nivasa,nqarncw,nuwdhd,pqgx,rffzbh,tnwjutw,ujia,yydjfm,yyesru,zivmx\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'aoatp,aymx,dubxhxmdxr,fmuukesl,jecnj,jqe[66 chars]ljvc' : Should be aoatp,aymx,dubxhxmdxr,fmuukesl,jecnj,jqexu,kgugweea,lczja,lvesh,oxsfrlwktz,qgjywbjw,tqievvgsaq,ulzknc,wupgljvc\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'csvv,dwauhgdb,enrnhp,gljvnjuigu,mqkwxq,mvrzmjny,onuicrvy,zmnglfgz' : Should be csvv,dwauhgdb,enrnhp,gljvnjuigu,mqkwxq,mvrzmjny,onuicrvy,zmnglfgz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'agze,ckuxma,gloplroirw,ixerlhp,kbgr,lbep[54 chars]bwiw' : Should be agze,ckuxma,gloplroirw,ixerlhp,kbgr,lbeppf,mtqyjyg,ntadsbcy,pgjbcv,sfhqzdgeyp,yrsxpcbbx,zkjiiobwiw\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'adcbeejn,lfnjmloj,lkexbut,obyuald,qznubdro,ufjik' : Should be adcbeejn,lfnjmloj,lkexbut,obyuald,qznubdro,ufjik\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'hvif,qkok,tadhgqcaxn,xhvzxtsqpv,zmkfxb' : Should be hvif,qkok,tadhgqcaxn,xhvzxtsqpv,zmkfxb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'aebklw,ezmrkl,imtx,jjmaafas,mbaogda,mbvr,nhni,rzuw,seztlloum,wpbwmklef' : Should be aebklw,ezmrkl,imtx,jjmaafas,mbaogda,mbvr,nhni,rzuw,seztlloum,wpbwmklef\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'cbvyvxvmbg,fnvlweehl,gsnpukcaz,qblnd,roq[39 chars]zfsk' : Should be cbvyvxvmbg,fnvlweehl,gsnpukcaz,qblnd,roqfr,sozkg,uqztcoxm,vewk,wfoe,wqgr,yzylg,zfsk\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'aexwlfz,kilovi,qzcqlywved,zomppa' : Should be aexwlfz,kilovi,qzcqlywved,zomppa\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'ansax,bbswcj,dblybon,degsoe,dnjgfmrqvj,h[60 chars]nmfg' : Should be ansax,bbswcj,dblybon,degsoe,dnjgfmrqvj,hwwil,navzy,tndacmjj,uqhahxss,wvbb,yxakgymtnj,zmqzonlnz,ztaoxnmfg\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'dhohg,ewuspjxx,hgcdzqcero,jovzzppout,lrt[73 chars]qtfe' : Should be dhohg,ewuspjxx,hgcdzqcero,jovzzppout,lrtcpimb,pyiprtbub,qbnlcrmi,tgxatavo,tmjib,whkhxplsv,wjeomzpurn,wlwchxgiul,yqtfe\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'cvhc,cvvla,cxavpztbl,cxzxqw,incrco,jcwpr[130 chars]tmxd' : Should be cvhc,cvvla,cxavpztbl,cxzxqw,incrco,jcwprjatuz,khzjio,mjssme,nexp,ngoq,ovfvt,ovtlcn,oyufima,ozqavvc,qrop,rerd,rttrriuf,skvkxvsr,syzay,ttydcrz,wiquupycmw,xged,zarxqa,zqupwwtmxd\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'eqvrfjwizj,gsyav,jqic,juhtpluxc,liiikvq,[41 chars]yqak' : Should be eqvrfjwizj,gsyav,jqic,juhtpluxc,liiikvq,oltpch,pymbqet,srcuuoeak,tahslykmi,wdvns,yqak\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'dsdp,hoom,kboc,kxknsgi,maqimuzah,nuwdmcw[58 chars]rlzi' : Should be dsdp,hoom,kboc,kxknsgi,maqimuzah,nuwdmcwa,pvbzpttrtt,rbchzkz,tmkjh,whmbnrbaur,wjlboq,wqxsfkl,xngrjrlzi\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bijcnjpu,gsdtw,iqouihbltr,nmbqxihubv,nyspanid,obmzigwu,rtuzn,xjtfd' : Should be bijcnjpu,gsdtw,iqouihbltr,nmbqxihubv,nyspanid,obmzigwu,rtuzn,xjtfd\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'gtobh,jntufgtmb,jrtx,lexniijgva,ppwlycmq,rfklhjsg,ugidcxm,wwldgfez' : Should be gtobh,jntufgtmb,jrtx,lexniijgva,ppwlycmq,rfklhjsg,ugidcxm,wwldgfez\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'beljasxr,bizwxjbq,bqda,cfbqkjxwr,dfhfutc[137 chars]cvsg' : Should be beljasxr,bizwxjbq,bqda,cfbqkjxwr,dfhfutcihs,eualsk,fsalc,gaqdirtacg,ibokxfqsf,kooopdzlnz,miqzw,ocmyfkqpl,onuvys,pbijxjpr,qacfqd,rjkebir,rlyosvlyxo,scbqkjicg,wikb,wqrfp,yeyooys,zcvsg\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bdtqkyykl,bsjmcervj,ewbupswsqi,ghjht,jlo[50 chars]iqik' : Should be bdtqkyykl,bsjmcervj,ewbupswsqi,ghjht,jlosehg,jprh,kazgnxq,lvpogitwy,opms,pveqvi,qyntd,xklfiqik\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'anxdzvk,aqfpyyepzt,bnvdlhmlq,ceuwxxy,dhs[89 chars]yalp' : Should be anxdzvk,aqfpyyepzt,bnvdlhmlq,ceuwxxy,dhsmgkpr,edmt,eifad,hrwopg,ispyx,jnek,kookvyz,nvciim,opjhmu,oreswe,szzp,ucjgx,vecbcip,wgisv,yalp\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'adlc,clheiay,cpsgc,dajxsw,gcrx,ihhddyrgs[119 chars]olnf' : Should be adlc,clheiay,cpsgc,dajxsw,gcrx,ihhddyrgsl,khdzuju,lhcvnpihuz,lsvuc,odjkjm,ppftdldbyv,pwjrrew,qbiqs,qcrzpnw,rpbg,ugedwuuo,vfbgme,wleacjvrpt,wymrbebe,xkaxllwb,ykolnf\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'ialf,jroj,kpirkqsk,pcnmqykwrk,srpu,yjsp' : Should be ialf,jroj,kpirkqsk,pcnmqykwrk,srpu,yjsp\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bvbzktsk,cltljaounb,gfke,hheaug,jrpccs,k[102 chars]zpii' : Should be bvbzktsk,cltljaounb,gfke,hheaug,jrpccs,kfddl,lipirol,ocjavompzn,ospzhttl,sekffjns,sogzzfux,tnttv,tyvnxy,utiitnrer,veklqsxcsv,vrcyh,xvfvbokjnv,zpii\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'cbscebhekc,cfnzflnoir,dnqtgnc,fvwc,gvmza[70 chars]yqte' : Should be cbscebhekc,cfnzflnoir,dnqtgnc,fvwc,gvmza,gzeclzq,ictr,jked,kiikiyhcvu,maeqsjrm,poilqgiynk,qjgdelv,xjinpi,xrueeyqte\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bbvcgcmriy,cscluyshp,ffqb,ffxge,fhqfqmwi[158 chars]njxj' : Should be bbvcgcmriy,cscluyshp,ffqb,ffxge,fhqfqmwi,gxtxakwiaw,ixyri,jnkca,pigyyi,pokbgb,qnfdac,rerfao,rfgfehumg,tibcjil,uxhmuxtaj,vmtprdgdmj,wyeqrhgkm,xchbakqg,xkywwsgr,xsgahcu,yuqlgenaz,yyzktq,zohno,zwuq,zxhnjxj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\pinil\\IRONLABS\\lab-functions\\mod\\testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 'bpjylkxc,efuhftzmi,exihfqblr,fuawgyr,fwf[107 chars]fckv' : Should be bpjylkxc,efuhftzmi,exihfqblr,fuawgyr,fwfrp,kcpx,nymgpya,optnzsehh,pakz,tahzvt,vidtydb,wabcnolgbg,wqwbtfypg,wwbahxrwo,xycnxmybj,yatbuyosh,ykexsoyc,zfckv\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.110s\n",
      "\n",
      "FAILED (failures=100)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_alpha(sort_alpha)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 12. Write a function to check if a given password is strong (at least 8 characters, at least one lower case, at least one upper case, at least one number and at least one special character). It should output True if strong and False if not.\n",
    "`Valid special characters: # @ ! $ % & ( ) ^ * [ ] { }`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def check_pass(string):\n",
    "    pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This will test your function \n",
    "test_pass(check_pass)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
